<template>
   <body>
      <div class="banner">
         <img id="show-icon" sizes="(min-width: 420px) 48.48vw, 68.22vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-20icon256/ShowDecbig.png 256w, https://ik.imagekit.io/theperfectpixl/tr:n-20icon1710/ShowDecbig.png 1710w, https://ik.imagekit.io/theperfectpixl/tr:n-20icon2400/ShowDecbig.png 2400w" src="https://ik.imagekit.io/theperfectpixl/ShowDecbig.png" alt="Showcase">
         <video playsinline autoplay loop muted preload="metadata" id="bannervideo">
            <source src="https://ik.imagekit.io/theperfectpixl/OptimusFilm.mp4" type="video/mp4">
         </video>
      </div>
      <div class="intro">
         <div class="text">
         This is a showcase for some of my favorite photos that I've taken over the years, ranging from the earliest days of my collection to just this month. To see the broader range of my gallery, check out various gallery tabs in navigation.
         </div>
      </div><br>
      <div style="flex: 1">
         <div class="body" id="big-image">
            <a href="https://ik.imagekit.io/theperfectpixl/BlackPunch.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/BlackPunch.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/BlackPunch.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/BlackPunch.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/BlackPunch.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/BlackPunch.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/BlackPunch.webp" height="400" width="300" alt="Scourge punching the camera."></a> <a href="https://ik.imagekit.io/theperfectpixl/ThundersClose.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/ThundersClose.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/ThundersClose.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/ThundersClose.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/ThundersClose.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/ThundersClose.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/ThundersClose.webp" height="400" width="300" alt="Siege Thundercracker in a dynamic pose."></a> <a href="https://ik.imagekit.io/theperfectpixl/AirWaspTree.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/AirWaspTree.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/AirWaspTree.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/AirWaspTree.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/AirWaspTree.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/AirWaspTree.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/AirWaspTree.webp" height="400" width="300" alt="Airrazor standing triumpant with a defeated Waspinator in a tree."></a> <a href="https://ik.imagekit.io/theperfectpixl/TronWalk.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/TronWalk.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/TronWalk.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/TronWalk.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/TronWalk.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/TronWalk.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/TronWalk.webp" height="400" width="300" alt="Animated Megatron walking."></a> <a href="https://ik.imagekit.io/theperfectpixl/CheetorSwing.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/CheetorSwing.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/CheetorSwing.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/CheetorSwing.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/CheetorSwing.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/CheetorSwing.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/CheetorSwing.webp" height="400" width="300" alt="Kingdom Cheetor swinging on a branch."></a> <a href="https://ik.imagekit.io/theperfectpixl/MegTankUnder.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/MegTankUnder.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/MegTankUnder.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/MegTankUnder.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/MegTankUnder.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/MegTankUnder.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/MegTankUnder.webp" height="400" width="300" alt="Cog being crushed under Megatron's tank treads."></a> <a href="https://ik.imagekit.io/theperfectpixl/PredaconsGroupAction.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/PredaconsGroupAction.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/PredaconsGroupAction.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/PredaconsGroupAction.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/PredaconsGroupAction.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/PredaconsGroupAction.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/PredaconsGroupAction.webp" height="400" width="300" alt="Dinobot and Blackarachnia rebel against Megatron."></a> <a href="https://ik.imagekit.io/theperfectpixl/RodCyc.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/RodCyc.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/RodCyc.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/RodCyc.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/RodCyc.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/RodCyc.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/RodCyc.webp" height="400" width="300" alt="Kingdom Rodimus is attacked by Kingdom Cyclonus."></a> <a href="https://ik.imagekit.io/theperfectpixl/MinorReach.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/MinorReach.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/MinorReach.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/MinorReach.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/MinorReach.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/MinorReach.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/MinorReach.webp" height="400" width="300" alt="Rodimus Minor reaches for his bow."></a> <a href="https://ik.imagekit.io/theperfectpixl/BulkWinFront.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/BulkWinFront.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/BulkWinFront.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/BulkWinFront.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/BulkWinFront.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/BulkWinFront.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/BulkWinFront.webp" height="400" width="300" alt="Bulkhead knocks Soundwave in the air towards the camera."></a> <a href="https://ik.imagekit.io/theperfectpixl/SkywarpLib.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/SkywarpLib.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/SkywarpLib.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/SkywarpLib.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/SkywarpLib.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/SkywarpLib.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/SkywarpLib.webp" height="400" width="300" alt="Skywarp sits on a bush."></a> <a href="https://ik.imagekit.io/theperfectpixl/WaveMinion.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/WaveMinion.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/WaveMinion.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/WaveMinion.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/WaveMinion.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/WaveMinion.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/WaveMinion.webp" height="400" width="300" alt="Soundwave commands his minion."></a> <a href="https://ik.imagekit.io/theperfectpixl/WindComfortClose.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/WindComfortClose.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/WindComfortClose.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/WindComfortClose.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/WindComfortClose.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/WindComfortClose.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/WindComfortClose.webp" height="400" width="300" alt="Windblade comforts Waspinator while Starscream and Rattrap scheme behind her."></a> <a href="https://ik.imagekit.io/theperfectpixl/LockEye.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/LockEye.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/LockEye.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/LockEye.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/LockEye.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/LockEye.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/LockEye.webp" height="400" width="300" alt="Lockdown looks through his hook."></a> <a href="https://ik.imagekit.io/theperfectpixl/Party.webp" class="image-link"> <img class="show-image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/Party.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/Party.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/Party.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/Party.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/Party.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/Party.webp" height="400" width="300" alt="Spinister and Soundwave send their minions on a play date."></a> <a href="https://ik.imagekit.io/theperfectpixl/ProwlParkour.webp" class="image-link"> <img class="index_image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/ProwlParkour.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/ProwlParkour.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/ProwlParkour.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/ProwlParkour.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/ProwlParkour.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/ProwlParkour.webp" height="400" width="300" alt="Prowl using his wheels to wall run."></a> <a href="https://ik.imagekit.io/theperfectpixl/MachShoulder.webp" class="image-link"> <img class="index_image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/MachShoulder.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/MachShoulder.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/MachShoulder.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/MachShoulder.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/MachShoulder.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/MachShoulder.webp" height="400" width="300" alt="RID Super Prowl looking over his shoulder."></a> <a href="https://ik.imagekit.io/theperfectpixl/StreakLean.webp" class="image-link"> <img class="index_image" sizes="(min-width: 1260px) 350px, 20.91vw" srcset="https://ik.imagekit.io/theperfectpixl/tr:n-size256/StreakLean.webp 256w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size700/StreakLean.webp 700w, https://ik.imagekit.io/theperfectpixl/tr:n-size1000/StreakLean.webp 1000w,
            https://ik.imagekit.io/theperfectpixl/tr:n-size1220/StreakLean.webp 1220w, https://ik.imagekit.io/theperfectpixl/tr:n-size1410/StreakLean.webp 1410w" src="https://ik.imagekit.io/theperfectpixl/StreakLean.webp" height="400" width="300" alt="War for Cybertron Earthrise Bluestreak leaning against a pole."></a>
         </div>
      </div>
   </body>
</template>

<style scoped>
.show-image {width: 22vw;}
#show-icon {
	width: 50%; 
	position: absolute;
	box-shadow: 0 0 0;
}
@media screen and (min-width: 1600px) {#show-icon {width: 60%;}}
@media screen and (max-width: 486px) {.show-image {width: 33vw;}}
@media screen and (max-width: 414px) {#show-icon {width: 70%;}}
</style>